### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by davidbrochart** [projectchrono/chrono#194]
I am trying to create a package on conda-forge: https://github.com/conda-forge/staged-recipes/pull/9965
But the CI fails with conflicts. Has anyone tried to to that?

**Comment by Benatti1991** [comment]
Hi David,
we are already building conda packages (they we are uploading them to project chrono channel); this being said, in the contrib/packaging_python/conda directory you can find conda recipes. 
BTW, I noticed that you have "ENABLE_MODULE_PYTHON=OFF", you should turn it ON in order to build the python module. 
This being said, don't hesitate to directly contact me, I'll be happy to help you in building the conda-forge package!
Simone

**Comment by davidbrochart** [comment]
Hi Simone,
Thanks for your answer. I saw the chrono channel, but I would like to have it in the conda-forge channel.
I had to set "ENABLE_MODULE_PYTHON=OFF" because of compilation issues. But now that I have enabled it I get conflicts:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=83937&view=logs

**Comment by Benatti1991** [comment]
Hi David,
I've seen your last build (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=84142) and it is failing because it does not find Python.h. Make sure that python.h is in the directory pointed by "DPYTHON_INCLUDE_DIR"
Simone

**Comment by davidbrochart** [comment]
Thanks for taking a look Simone. I had try other things, now it fails with error "directorout typemap for plain pointer not implemented":
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=84166

**Comment by Benatti1991** [comment]
Oh, I remember it. The code in master branch is not compatible with SWIG 4.0. You could:
- build the code in the develop branch (which I suggest)
- Downgrade swig to 3..012

**Comment by davidbrochart** [comment]
Thanks Simone, downgrading swig worked. `conda-forge` needs a release so taking the develop branch is not an option.

**Comment by davidbrochart** [comment]
Actually, it doesn't install the Python package: https://github.com/conda-forge/staged-recipes/pull/9965
The feedstock is [here](https://github.com/conda-forge/pychrono-feedstock), so you can `conda install -c conda-forge pychrono`, but then `import pychrono` doesn't work. Any idea?

**Comment by Benatti1991** [comment]
HI David,
for some reason the package is in the wrong directory. I found it in 
`/home/user_name/miniconda3/envs/env_name/share/chrono/python/pychrono`
Instead of 
`/home/user_name/miniconda3/envs/env_name/lib/python_ver/site-packages/pychrono`

**Comment by davidbrochart** [comment]
Thanks Simone, it works if I copy the package in `site-package`, but only for Linux. For OS X I have a `illegal instruction` error when importing pychrono. Do you know where that can come from?

**Comment by Benatti1991** [comment]
We don't, we are working to fix the issue on MasOS, but currently I don't have access to a Mac machine so it's quite difficult for me to fix the problem. Are you experiencing the same issue mentioned [here](https://github.com/projectchrono/chrono/issues/191)?

**Comment by davidbrochart** [comment]
It could be related but I'm not sure. I don't have a Mac machine either, I just saw the error in the CI, which makes it difficult to debug too. I disabled OS X for now. Thanks for your answer!

**Comment by davidbrochart** [comment]
Hi Simone, any news about the OSX issue? Here is the error in the CI: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=95184

**Comment by Benatti1991** [comment]
I don't know what's in test.py line 2, but I assume it is "import pychrono". We are experiencing this issue and I couldn't get to work on a Mac machine to inspect it, sorry.

**Comment by Benatti1991** [comment]
Hi David,
we are trying to solve the issue with MacOS. 
Could you please tell me which compiler and SWIG version you are using to build PyChrono for Mac?
Thanks,
Simone

**Comment by davidbrochart** [comment]
Hi Simone,
We use `swig 3.0.12` (see the [recipe](https://github.com/conda-forge/pychrono-feedstock/blob/master/recipe/meta.yaml)). The compilers in the [CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=95184) are:
```
+CC=x86_64-apple-darwin13.4.0-clang
+CXX=x86_64-apple-darwin13.4.0-clang++
```
Thanks for working on it!

**Comment by rainergericke** [comment]
Hi David,

we were successful building chrono with python enabled. Actually we cannot support mkl and cascade and every SolidWorks related stuff. Unfortunately I cannot help you building Conda packages because I don't have any idea about it. I use homebrew as package manager, but when you see what I did with homebrew, you can imagine what to do with Conda hopefully.

brew install cmake doxygen graphviz gnuplot eigen python swig
brew install glm glew glfw ninja irrlicht ffmpeg

homebrew installs python-3.7.5 and swig-4.0.1. That seems to be a good combination, but we have to consider that python2 is still present and we have to be sure to point to python3 whenever necessary in the cmake calls. It should be possible to build chrono with python support now. Command line tools like demo_python_1.py must be started with

python3 demo_python_1.py

The most python examples need Irrlicht for 3D graphics, they have to be wrapped into a Mac application bundle. There is a nicer helper available: py2app it must be installed with

pip3 install py2app

Good Luck

Rainer

**Comment by Benatti1991** [comment]
Rainer,
thank you again for your help. I'm adding a couple of consideration related to this particular issue:

- Python and pip version are determined by Anaconda environment, so the right ones are picked given that the environment is activated.
- SWIG 4 seems to be the solution to our problem but since you are building the code from the master branch it would not compile because chrono 4.0 release isn't compatible with SWIG 4. Good news: chrono 5 is likely to be released soon.
Simone

**Comment by davidbrochart** [comment]
Thanks Rainer and Simone. I guess it's best to wait until chrono 5 is released then. Thanks again!

**Comment by rserban** [comment]
David,
The 5.0 release will only happen end of January, mid-February (if we get to finish up everything we need for it).  Also, it would be good to know **before** the release if this also works for your setup.  So far we have only Rainer's experience as the unique data point.
Long story short, could you maybe try this out with the latest code in the 'develop branch? And let us know how it goes?
--Radu

**Comment by davidbrochart** [comment]
Hi Radu, the thing is that conda-forge requires a release, and forbids to take just a branch. Could you please make a "dummy" release, on the develop branch?

**Comment by rserban** [comment]
What constitutes a "dummy" release?  Will a tag be enough? If so, any particular name for it?

**Comment by davidbrochart** [comment]
Actually, let me try without a release, I might be able to download a tarball through `https://github.com/projectchrono/chrono/tarball/develop`.

**Comment by davidbrochart** [comment]
@rserban I tried to disable irrlicht for now with `-DENABLE_MODULE_IRRLICHT:BOOL=OFF`, but I'm still getting an error that seems related to irrlicht:
```
[ 99%] Linking CXX shared library ../../../lib/libChronoModels_vehicle.so
[ 99%] Built target ChronoModels_vehicle
Scanning dependencies of target vehicle_swig_compilation
[100%] Swig compile ChModuleVehicle.i for python
/home/conda/feedstock_root/build_artifacts/pychrono_1576113474141/work/src/chrono_python/ChDriver.i:34: Error: Unable to find 'dimension2d.h'
```

**Comment by rserban** [comment]
You're right, the vehicle module wrapper should conditionally include irrlicht-related stuff.  We'll look into fixing this.   In the meantime, you should also disable the vehicle module (ENABLE_MODULE_VEHICLE).

**Comment by rserban** [comment]
@davidbrochart I pushed a fix to allow building the python wrapper for Chrono::Vehicle even with Irrlicht disabled.   Please let us know if you get this working on Mac

**Comment by rainergericke** [comment]
I could build it on the Mac, we don't have 'text mode' vehicle example in python yet. The demo_python_*.py examples work.

**Comment by rainergericke** [comment]
New problem on the Mac. When I build chrono with vehicle and Irrlicht the build process works.
The python vehicle examples run into an error:
AttributeError: module 'pychrono.vehicle' has no attribute 'ChWheeledVehicleIrrApp'
The other Irrlicht based examples work.

**Comment by rserban** [comment]
Yeah, looks like my "fix" broke things.

**Comment by rserban** [comment]
Rainer, I pushed a fix to the fix.

**Comment by davidbrochart** [comment]
I still get a `illegal instruction` error: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=103125

**Comment by rainergericke** [comment]
Things seem to be functional on the Mac now. py_chrono can be configured with or without Irrlicht.

**Comment by Benatti1991** [comment]
Hi David,
we forgot to mention that we were able to build and import pychrono using CLang 11.
Would  it be possible for you to update to that version?
Thanks,
Simone

**Comment by davidbrochart** [comment]
Hi Simone, sorry for the late reply. In conda-forge, the version of clang is 9.0.0, and I don't think we can use a newer version. It would be nice if you could check that it doesn't work with 9.0.0 on your side, so that we know that the clang version is indeed the issue.

**Comment by davidbrochart** [comment]
Actually, what do you mean by clang 11? This version of clang doesn't exist yet.

**Comment by rserban** [comment]
I'm not an OSX user, but apparently Apple re-versions clang to match the XCode version.  
According to https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_11.x_(since_Free_On-Device_Development), Xcode 11.3 (Apple clang version 11.0.0) seems to be based on LLVM 8.0.0.

**Comment by rainergericke** [comment]
Radu is right. Apple has its own naming scheme. When we talk about clang versions we should also mention which compiler we mean. The llvm compilers can also be built on the Mac and they are able to build chrono. It is also possible that not every Mac user uses the latest MacOS and/or the latest Xcode release, so David may be also right. This is my configuration:
MacOS 10.15.2 Catalina
clang Apple clang version 11.0.0 (clang-1100.0.33.16)
Xcode 11.3

**Comment by davidbrochart** [comment]
The problem is that on conda-forge we have strict requirements on compiler versions. Today we use clang 9.0.0. It would be nice to check that on your side it doesn't work with clang 9.0.0.

**Comment by rainergericke** [comment]
Which answer do you get with this command:
$ clang --version

**Comment by davidbrochart** [comment]
I can't do that easily because it runs on the CI, but I can see in the log that it's 9.0.0.

**Comment by rainergericke** [comment]
It would be good to know, because once upon a time also Apple clang-9.0.0 existed and it is quite far away from LLVM clang-9.0.0. I also have llvm-clang on my Mac and I can give it a try.

**Comment by davidbrochart** [comment]
I was able to run the command: `clang version 9.0.0 (tags/RELEASE_900/final)`

**Comment by rainergericke** [comment]
It looks like LLVM. I will try it.

**Comment by rainergericke** [comment]
PyChrono + LLVM-clang + SWIG-4.0.1 + python3 works.

**Comment by davidbrochart** [comment]
So now we need to compare our environments. The compilation log on the CI is here: https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/103125/logs/20
Could you please send me yours?

**Comment by rainergericke** [comment]
Before I send my log file, just a remark, your compiler has been built in the environment
x86_64-apple-darwin13.4.0-clang. I use x86_64-apple-darwin19.2.0 for Apple-clang and for LLVM-clang. That means you are working with an older Xcode/MacOS. But it doesn't matter - it seems to me your package builds well and complete as configured. The problem might be, that the environment variable PYTHONPATH is not set correctly in the test situation. Cmake gives an information how it has to be set. There are two possibilities: one for runing in the build directory and an other for running in the install directory.

**Comment by davidbrochart** [comment]
But conda does't make any use of the PYTHONPATH environment variable. Also, after installation we `cp -r $PREFIX/share/chrono/python/* $PREFIX/lib/python$HOST_PY_VER/site-packages`. I am trying to test with `python -c "import os, site; os.environ['PYTHONPATH'] = site.getsitepackages()[0]; import pychrono"`. However, even if that works, we won't be able to do that in the user's environment.

**Comment by Benatti1991** [comment]
The pythonpath variable is not likely to be the issue. The interpreter finds pychrono, otherwise you would get a different error.

**Comment by davidbrochart** [comment]
Indeed it didn't fix the issue.
@isuruf mentioned that we should not link to libpython3.8.dylib, because the python executable is statically linked to the python library, so if an extension is linked to the shared library, it'll bring in 2 copies.
Is there a way to not link to the python library currently?

**Comment by davidbrochart** [comment]
Also, there quite a lot of compiler warnings in OSX (https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/106163/logs/20) that we don't have in Linux (https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/106163/logs/16).

**Comment by rainergericke** [comment]
If you are able to build the whole package, the warnings don't matter. The end product will work. Seems the clang compilers are more penible and verbose than others. Does the c++ stuff work?

**Comment by davidbrochart** [comment]
Not sure about the warnings being harmless: https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10
I don't know about the C++, how can I test it?

**Comment by rainergericke** [comment]
Depending on the cmake configuration some tests and/or demos are built. The best way would be to activate the unit tests. One of the basic demos is 'demo_CH_EulerAngles.app'. Most c++ demos are built as MacOS application bundles. To start a bundle from the command line you must write:
$ demo_CH_EulerAngles.app/Content/MacOS/demo_CH_EulerAngles
You must go to the directory where the bundles sits before you can start it.
When you have unit tests activated, you have programs with name beginning with utest....
you can start them as normal programs you know from Linux.

**Comment by cekees** [comment]
Hi @rserban, is there any chance we'll get a new release soon? I believe the issue is fixed, but the conda forge package is waiting on a new chrono release. Let us know if we can help test. /cc @davidbrochart .

**Comment by davidbrochart** [comment]
@cekees I'm not sure we are talking about the same issue. This issue has to do with pychrono failing in the CI on OSX. AFAIK this has not been fixed yet.

**Comment by rserban** [comment]
@cekees We are planning on a release by the end of the month.

**Comment by cekees** [comment]
OK, thanks. @davidbrochart I see. Can you enable the osx version of the conda build and just allow the warnings so @ejtovar can test on osx? I tend to agree with @rainergericke that  disabling the demos and enabling the unit tests in the conda pacakge would be a good way forward. I don't think the demos should be built in the conda package. To be clear, my goal here is to get the chrono conda package functional for both linux and osx.

**Comment by davidbrochart** [comment]
> OK, thanks. @davidbrochart I see. Can you enable the osx version of the conda build and just allow the warnings so @ejtovar can test on osx?
I don't see what you mean, there is [this PR](https://github.com/conda-forge/pychrono-feedstock/pull/6) where we enable the OSX build. The test fails so this will not help @ejtovar test.

**Comment by cekees** [comment]
I meant enable the osx build of chrono on conda-forge. I do see that your conda-forge chrono feedstock PR to enable OSX is failing to build on OSX, but I don't understand the issues.  I gather from comments above that @rainergericke and @Benatti1991 have functioning osx builds.  Should @ejtovar just get chrono from the chrono channel mentioned above or homebrew for now? @davidbrochart I can't tell from comments above whether you were ever able to build a pre-release version of chrono or not on osx.  Can you confirm that  the upcoming release of chrono is going to fix the conda-forge package?

**Comment by davidbrochart** [comment]
@cekees I have never been able to get pychrono to work on OSX in conda-forge. When we import pychrono we get a `Illegal instruction` error. @rainergericke and @Benatti1991 have functioning OSX builds *locally*, but we need it in the CI. The upcoming release is likely not to fix the conda-forge package because the PR takes the `develop` branch and the release will be based on it.
I don't advise that @ejtovar get pychrono from another channel because it can lead to binary inconsistency. I thought he was working on a workaround in Proteus that would enable OSX by disabling pychrono just for OSX?

**Comment by Benatti1991** [comment]
This thread is becoming a bit confusing so, @davidbrochart , how does your situation look like now? Can you build PyChrono on the CI? Can you import? If not, what is the error that is thrown?
Also, do you want us to do something (test or whatever)?
Thanks,
Simone

**Comment by davidbrochart** [comment]
@Benatti1991 the issue is still there, I launched the build today with the develop branch and we still get an `Illegal instruction` when we import pychrono: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=118312&view=logs&jobId=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&j=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&t=4a56039b-7269-50ae-de7a-538e91e6de06
If you see something wrong either in the recipe or in the build log, that would help. Thanks!

**Comment by cekees** [comment]
Looking at the build.sh here: https://anaconda.org/projectchrono/pychrono/4.0.0/download/osx-64/pychrono-4.0.0-py36_402.tar.bz2 and just trying to recover what built in the past, maybe turn off  testing, benchmarking, and gmock? Maybe also turn off OpenMP?

```
# set MKL vars                                                                                                                                                                                
export MKL_INTERFACE_LAYER=LP64
export MKL_THREADING_LAYER=INTEL
CONFIGURATION=Release
# Configure step                                                                                                                                                                              
cmake -DCMAKE_INSTALL_PREFIX=$PREFIX \
 -DCMAKE_PREFIX_PATH=$PREFIX \
 -DCMAKE_SYSTEM_PREFIX_PATH=$PREFIX \
 -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Xpreprocessor -Wno-unused-command-line-argument" \
 -DCH_INSTALL_PYTHON_PACKAGE=$SP_DIR \
 -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON \
 -DPYTHON_INCLUDE_DIR:PATH=$PREFIX/include/python$MY_PY_VER \
 -DPYTHON_LIBRARY:FILEPATH=$PREFIX/lib/${PY_LIB} \
 -DCMAKE_BUILD_TYPE=$CONFIGURATION \
 -DEIGEN3_INCLUDE_DIR=/usr/local/include/eigen3 \
 -DENABLE_MODULE_IRRLICHT=ON \
 -DENABLE_MODULE_POSTPROCESS=ON \
 -DENABLE_MODULE_VEHICLE=ON \
 -DENABLE_MODULE_PYTHON=ON \
 -DBUILD_DEMOS=OFF \
 -DBUILD_TESTING=OFF \
 -DBUILD_BENCHMARKING=OFF \
 -DBUILD_GMOCK=OFF \
 -DENABLE_MODULE_CASCADE=ON \
 -DCASCADE_INCLUDE_DIR=$HOME/miniconda3/include/oce \
 -DCASCADE_LIBDIR=$HOME/miniconda3/lib \
 -DENABLE_MODULE_MKL=ON \
 -DMKL_INCLUDE_DIR=$HOME/miniconda3/include \
 -DMKL_RT_LIBRARY=$HOME/miniconda3/lib/libmkl_rt.dylib \
 ./..
```

**Comment by davidbrochart** [comment]
@cekees testing and benchmarking are already turned off. I can try to turn off gmock and openmp.

**Comment by cekees** [comment]
OK, seems like it's worth a shot. For what we need the chrono package for you could also disable FSI and VEHICLE, but I realize where reaching at this point. Is it possible to get the azure image and run it locally to see if we can diagnose?

**Comment by davidbrochart** [comment]
I will try to disable FSI and VEHICLE next. I don't think it's possible to get the azure image or to log into the machine. That's why it's difficult to debug.
Also the default Anaconda channel and conda-forge are different environments, so a successful build on the default channel doesn't mean it will work on conda-forge.

**Comment by davidbrochart** [comment]
@cekees same result when disabling all the above: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=118674&view=logs&j=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&t=4a56039b-7269-50ae-de7a-538e91e6de06

**Comment by Benatti1991** [comment]
FSI is not exposed to Python so it's unlikely to cause any issue. Try disabling vehicle and other submodules (subprocess and most importantly Irrlicht) and let's see what happens.
I'm having an hard time understanding the compiler version thing, but please double check that you are using the same version @rainergericke  is using.

**Comment by rainergericke** [comment]
A word about FSI on the Mac: FSI depends on CUDA. Since Apple only uses Intel or AMD graphic cards NVIDIA dropped the development of CUDA SDKs for MacOS. CUDA itself would run on Macs with compatible NVIDIA cards only. CUDA was necessary for Chrono::Parallel because it delivers the THRUST template library. With macOS Catalina it has become impossible to install CUDA at all. THRUST exists as an open source project yet and the last release is compatible with Chrono::Parallel. Actually CUDA based solutions will not work on the Mac. 

OpenMP on the Mac needs some tweaks. Be sure to provide the right compiler options for C++ and C: '-Xclang -fopenmp' and the linker option '-lomp'. The runtime library libomp.dylib is not delivered automatically - it has to be built and installed before building chrono.

**Comment by davidbrochart** [comment]
@Benatti1991 Vehicle and Irrlicht are already disabled. By subprocess do you mean `-DENABLE_MODULE_POSTPROCESS:BOOL=OFF`? There is no hit when I grep SUBPROCESS in chrono.
The compilers are the same I already mentioned before:
```
+CC=x86_64-apple-darwin13.4.0-clang
+CXX=x86_64-apple-darwin13.4.0-clang++
```
And there's nothing we can do about it AFAIK.

@rainergericke I disabled openmp.

**Comment by rserban** [comment]
@davidbrochart Have you tried to reproduce this environment (matching the exact compiler, SWIG version, etc) on a stand-alone Mac and build the Chrono::Python module from sources?  That would give more clues on where the issues actually are.   Otherwise, it's quite difficult to debug this with so little control. 

@rainergericke is the only one on our side with access to a Mac.  Rainer, do you think it would be possible to try building PyChrono with the exact compiler David listed and see if you can run the python demos?

**Comment by davidbrochart** [comment]
@rserban No, I don't have a Mac.

**Comment by rainergericke** [comment]
@rserban I can try to use the conda system, but it will take a while since I am a python agnostic.

**Comment by rserban** [comment]
> @rserban I can try to use the conda system, but it will take a while since I am a python agnostic.

Rainer, before that I was hoping you might be able to build Chrono (including the Chrono::Python module) locally from sources, just like you did in the past, but using the exact compiler version mentioned above:
```
+CC=x86_64-apple-darwin13.4.0-clang
+CXX=x86_64-apple-darwin13.4.0-clang++
```

One step at a time, I cannot think of any other way to isolate where the problem is.

**Comment by Benatti1991** [comment]
I agree with @rserban, what conda builders do is basically putting files in the right place but if you are using the same compiler there's no reason to have a different behaviour.

**Comment by davidbrochart** [comment]
Actually what you can do is run the `build-locally.py` script from https://github.com/conda-forge/pychrono-feedstock/pull/6. That way you will have the closest environment from the CI.

**Comment by cekees** [comment]
From cond-forge gitter channel: "Illegal instruction is normally stemming from the fact that you compile code with e.g. SSE4 or POPCNT enabled while the CI processor has no support for it."

**Comment by rserban** [comment]
Is the test not performed on the same node?
From one of the logs posted above, it looks like SSE4 is available when configuring Chrono:
```
-- Seaching for SSE...
-- Performing Test DETECTED_SSE_42
-- Performing Test DETECTED_SSE_42 - Success
-- Performing Test DETECTED_SSE_41
-- Performing Test DETECTED_SSE_41 - Success
-- Performing Test DETECTED_SSE_30
-- Performing Test DETECTED_SSE_30 - Success
-- Performing Test DETECTED_SSE_20
-- Performing Test DETECTED_SSE_20 - Success
-- Performing Test DETECTED_SSE_10
-- Performing Test DETECTED_SSE_10 - Success
--   Found SSE 4.2 extensions, using flags:  -msse4.2 -mfpmath=sse
-- Searching for AVX...
-- Performing Test DETECTED_AVX_20
-- Performing Test DETECTED_AVX_20 - Success
-- Performing Test DETECTED_AVX_10
-- Performing Test DETECTED_AVX_10 - Success
--   Found AVX 2.0 extensions, using flags:  -mavx2
```

**Comment by davidbrochart** [comment]
I had some patches to remove SSE, AVX, NEON and FMA flags from `src/chrono_python/CMakeLists.txt`, but it looks like it is now in `src/CMakeLists.txt`. I will update the patches, but as we had them before I don't have too many hopes.

**Comment by cekees** [comment]
Thanks, David. The only other idea I have is to try to switch the OSX build to different CI infrastructure as the docs indicate is possible here: https://conda-forge.readthedocs.io/en/latest/ciservices.html.

**Comment by davidbrochart** [comment]
Actually we found a Mac machine where the same issue shows up, so it won't be necessary to change the CI infrastructure.
I don't know how to debug that though, I guess I can compile the unit tests on this machine and try to run them.

**Comment by isuruf** [comment]
@davidbrochart, try using https://github.com/pkgw/elfx86exts on the built library to see what the minimal instruction set used.

**Comment by davidbrochart** [comment]
Thanks @isuruf, I will try that (probably on Monday though!).

**Comment by davidbrochart** [comment]
The OSX build now works (https://github.com/conda-forge/pychrono-feedstock/pull/6), although it is not clear why.
I can wait until the next release of pychrono (5.0.0) or see if it works for v4.0.0 and merge it right now, what do you prefer?

**Comment by rainergericke** [comment]
That is good news. I suggest to wait for pychrono 5.0.0, it will come with significant improvements.

**Comment by davidbrochart** [comment]
FYI, you can now `conda install pychrono -c conda-forge` and it should work on Linux and OSX. Thanks everybody!

**Comment by rserban** [comment]
@davidbrochart, we released 5.0 yesterday.

**Comment by davidbrochart** [comment]
Yes, this is the version that is packaged in conda-forge.
