### ISSUE TITLE
[BUG] Chrono 9.0 release - "cannot open include file 'chrono_thirdparty/chpf/particle_writer.hpp'"

### ISSUE THREAD

**Issue by kjgbrt** [projectchrono/chrono#605]
**Summary**

Using Chrono 9.0 (zipped source file from https://github.com/projectchrono/chrono/releases/tag/9.0.1) and trying to install GPU module. Have a functional nvcc v12.3 (verified with cuda-samples), and have added appropriate flags for architecture and allowing unsupported compiler (secondary error). when try to compile project & demos, get following error: 
```
1>C:\ws\chrono-gpu-test\src\chrono_gpu\physics\ChSystemGpu_impl.cpp(30,10): error C1083: Cannot open include file: 'chrono_thirdparty/chpf/particle_writer.hpp': No such file or directory
```  

all GPU demos fail to compile, other demos are successful.

I looked at Github page, and the submodule link for "chpf" is broken (link on page: https://github.com/projectchrono/chrono/tree/release/9.0/src/chrono_thirdparty), clicking the link (https://github.com/projectchrono/chrono/blob/release/9.0/src/chrono_thirdparty/chpf) does nothing. Other submodule links on the page do function.

I believe there may have been a mispackaged and now missing submodule, and either the code or a workaround is needed.

**Chrono Version and Platform**
* Chrono 9.0.1 (from zipped source file provided in release tag)
* Windows 10
* MS Visual Studio 17.10 (msc 1940) (note: added in "allow-unsupported-compiler" flag)
* CUDA SDK 12.3 with compatible GPU hw / architecture

**Expected Behavior**

Chrono project compiles GPU demo programs

**Actual Behavior**

missing file error. 

**Steps to Reproduce**

1. download source code (zip) from https://github.com/projectchrono/chrono/releases/tag/9.0.1 and unpack
2. ensure CUDA SDK 12.3 is installed and verified to function
3. configure / generate makefile with appropriate flags, including
  1. ENABLE_MODULE_GPU = true
  2. CUDA_NVCC_FLAGS = `-arch=sm_89 -allow-unsupported-compiler`
4. compile in Visual Studio 2022 (17.10)
**Further Information, Files, and Links**

n/a

**Comment by kjgbrt** [comment]
additionally, this is visible in .gitmodules: 
```
[submodule "src/chrono_thirdparty/chpf"]
	path = src/chrono_thirdparty/chpf
	url = https://gitlab.com/uwsbel/chpf.git
```

this may be the source of the issue

**Comment by rserban** [comment]
This is a GitHub issue: release archives (zip or tar.gz) do not include code for any submodules.
There are numerous requests for them to fix this, but no indication that this will be done. 

One solution is for you to clone the Chrono repository and checkout the `release/9.0` branch.
