### ISSUE TITLE
Fails to build with OCCT 8.0

### ISSUE THREAD

**Issue by MehdiChinoune** [projectchrono/chrono#754]
**Summary**

Fails to build with OCCT 8.0

**Chrono Version and Platform**

chrono 10.0.0
It applies to any platoform

**Details**

```
  D:/_/B/src/chrono-10.0.0/src/chrono_cascade/ChCascadeDoc.cpp:41:5: error: unknown type name 'TDF_LabelSequence'
     41 |     TDF_LabelSequence child_labels;
        |     ^
  D:/_/B/src/chrono-10.0.0/src/chrono_cascade/ChCascadeDoc.cpp:87:9: error: unknown type name 'TDF_LabelSequence'
     87 |         TDF_LabelSequence refchild_labels;
        |         ^
  D:/_/B/src/chrono-10.0.0/src/chrono_cascade/ChCascadeDoc.cpp:284:5: error: unknown type name 'TDF_LabelSequence'
    284 |     TDF_LabelSequence root_labels;
        |     ^
  D:/_/B/src/chrono-10.0.0/src/chrono_cascade/ChCascadeDoc.cpp:335:5: error: unknown type name 'TDF_LabelSequence'
    335 |     TDF_LabelSequence root_labels;
        |     ^
  4 errors generated.
```

**Comment by rserban** [comment]
Chrono::CASCADE does *not* work with OCCT 8.0.
Please see the Chrono documentation: https://api.projectchrono.org/module_cascade_installation.html.

**Comment by MehdiChinoune** [comment]
> Chrono::CASCADE does _not_ work with OCCT 8.0. Please see the Chrono documentation: https://api.projectchrono.org/module_cascade_installation.html.

Yes, I know. I am a packager I want to update occt-8

**Comment by stefano2734** [comment]
Occt 8.0.0p1 with hotfixes available.

**Comment by rserban** [comment]
@MehdiChinoune - there are a couple of issues with keeping up-to-date with the latest dependency versions:
1. We do not always have the bandwidth to do that.
2. We must ensure that users who are not ready or cannot upgrade to the latest versions can still use the corresponding Chrono feature.

If you can provide a PR that allows using OCCT 8.0 while also maintaining backward compatibility with the currently supported versions, we'd be more than happy to review and merge it.

Thanks,
--Radu

**Comment by MehdiChinoune** [comment]
chrono package is not that popular among linux distros to worth the effort.
I will drop it if necessary. That's it.

**Comment by stefano2734** [comment]
OCCT 8.0.1 available.
https://github.com/Open-Cascade-SAS/OCCT/releases/tag/V8.0.1
